{
    'name': 'Product Pack',
    'version': '17.0.1.0.0',
    'category': 'Sales',
    'summary': 'Manage Products as Pack',
    'description': """Selling products in a pack is a great way to raise average 
    sales price per product, to serve customers with products that make their 
    lives easier, and to leverage current products into new and different ones.
    They are profitable for smaller businesses as well as large ones.""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['sale_management', 'stock', 'event', 'website_sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/feedback_view.xml',
        'report/feedback_template.xml',
        'report/feedback_thank_you_template.xml',
        'report/event_activity_report.xml',
        'report/event_report_print.xml',
        'views/event_type_form_inherit.xml',
        'data/event_activities.xml',
        'data/data_banquet_types.xml',
        'views/event_view_form_inherit.xml',
        'views/product_product_views.xml',
        'views/res_partner_view.xml',
        'views/banquet_type.xml',
        'report/sale_order_inherit.xml',
        # 'data/product_data.xml',
        'views/event_menu_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/personnel_views.xml',
        'views/calendar_inherit_view.xml',
        'views/job_category_views.xml',
        'data/sequence_data.xml',
        'views/quote_configure_template.xml',
        'static/description/js/script.js',
        'views/quote_thank_you_template.xml',
        'views/account_move_views.xml',
        'views/invoice_folder_view.xml',
    ],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
